"""empty message

Revision ID: 63e836e01f77
Revises: d0ee7a85b354
Create Date: 2026-10-06 01:25:21.714674

"""
from typing import Sequence, Union

import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '63e836e01f77'
down_revision: Union[str, Sequence[str], None] = 'd0ee7a85b354'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cacheddata',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hash', sqlmodel.sql.sqltypes.AutoString(length=40), nullable=False),
    sa.Column('data', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cacheddata_hash'), 'cacheddata', ['hash'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cacheddata_hash'), table_name='cacheddata')
    op.drop_table('cacheddata')
    # ### end Alembic commands ###
